# Generated by Django 4.2.10 on 2024-06-24 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at']},
        ),
    ]
